config/routes.rb
Rails.application.routes.draw do
  resources :escolas
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :nome, :sobrenome, :email, :telefone, :endereco, :obs, :numero, presence: true
end

app/models/escola.rb
class Escola < ActiveRecord::Base
    validates :nome, :turma, :numeroSala, :professor, :matricula, :turno, :escola, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:nome, :sobrenome, :email, :telefone, :endereco, :obs, :numero)
    end
end

app/controllers/escolas_controller.rb
class EscolasController < ApplicationController
  before_action :set_escola, only: [:show, :edit, :update, :destroy]

  # GET /escolas
  # GET /escolas.json
  def index
    @escolas = Escola.all
  end

  # GET /escolas/1
  # GET /escolas/1.json
  def show
  end

  # GET /escolas/new
  def new
    @escola = Escola.new
  end

  # GET /escolas/1/edit
  def edit
  end

  # POST /escolas
  # POST /escolas.json
  def create
    @escola = Escola.new(escola_params)

    respond_to do |format|
      if @escola.save
        format.html { redirect_to @escola, notice: 'Escola was successfully created.' }
        format.json { render :show, status: :created, location: @escola }
      else
        format.html { render :new }
        format.json { render json: @escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /escolas/1
  # PATCH/PUT /escolas/1.json
  def update
    respond_to do |format|
      if @escola.update(escola_params)
        format.html { redirect_to @escola, notice: 'Escola was successfully updated.' }
        format.json { render :show, status: :ok, location: @escola }
      else
        format.html { render :edit }
        format.json { render json: @escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /escolas/1
  # DELETE /escolas/1.json
  def destroy
    @escola.destroy
    respond_to do |format|
      format.html { redirect_to escolas_url, notice: 'Escola was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_escola
      @escola = Escola.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def escola_params
      params.require(:escola).permit(:nome, :turma, :numeroSala, :professor, :matricula, :turno, :escola)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/escolas_helper.rb
module EscolasHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sobrenome %><br>
    <%= f.text_field :sobrenome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :obs %><br>
    <%= f.text_area :obs %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editar Contat</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listar Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Endereço</th>
      <th>Obs:</th>
      <th>Número</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.nome %></td>
        <td><%= contact.sobrenome %></td>
        <td><%= contact.email %></td>
        <td><%= contact.telefone %></td>
        <td><%= contact.endereco %></td>
        <td><%= contact.obs %></td>
        <td><%= contact.numero %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>Novo Contato</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contact.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @contact.sobrenome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @contact.telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @contact.endereco %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @contact.obs %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @contact.numero %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/escolas/_form.html.erb
<%= form_for(@escola) do |f| %>
  <% if @escola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@escola.errors.count, "error") %> prohibited this escola from being saved:</h2>

      <ul>
      <% @escola.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :turma %><br>
    <%= f.text_field :turma %>
  </div>
  <div class="field">
    <%= f.label :numeroSala %><br>
    <%= f.text_field :numeroSala %>
  </div>
  <div class="field">
    <%= f.label :professor %><br>
    <%= f.text_field :professor %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :turno %><br>
    <%= f.text_field :turno %>
  </div>
  <div class="field">
    <%= f.label :escola %><br>
    <%= f.text_field :escola %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/escolas/edit.html.erb
<h1>Editar Escola</h1>

<%= render 'form' %>

<%= link_to 'Show', @escola %> |
<%= link_to 'Back', escolas_path %>

app/views/escolas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listar Escola</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Turma</th>
      <th>Numerosala</th>
      <th>Professor</th>
      <th>Matricula</th>
      <th>Turno</th>
      <th>Escola</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @escolas.each do |escola| %>
      <tr>
        <td><%= escola.nome %></td>
        <td><%= escola.turma %></td>
        <td><%= escola.numeroSala %></td>
        <td><%= escola.professor %></td>
        <td><%= escola.matricula %></td>
        <td><%= escola.turno %></td>
        <td><%= escola.escola %></td>
        <td><%= link_to 'Show', escola %></td>
        <td><%= link_to 'Edit', edit_escola_path(escola) %></td>
        <td><%= link_to 'Destroy', escola, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Escola', new_escola_path %>

app/views/escolas/new.html.erb
<h1>New Escola</h1>

<%= render 'form' %>

<%= link_to 'Back', escolas_path %>

app/views/escolas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @escola.nome %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @escola.turma %>
</p>

<p>
  <strong>Numerosala:</strong>
  <%= @escola.numeroSala %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @escola.professor %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @escola.matricula %>
</p>

<p>
  <strong>Turno:</strong>
  <%= @escola.turno %>
</p>

<p>
  <strong>Escola:</strong>
  <%= @escola.escola %>
</p>

<%= link_to 'Edit', edit_escola_path(@escola) %> |
<%= link_to 'Back', escolas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Senai App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <%= yield %>
    </div>
</body>
</html>